name: BumpVersion
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version'
        required: true
      minor_version:
        description: 'Minor version'
        required: true
      patch_version:
        description: 'Patch version'
        required: true

jobs:
  run:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby 3.1.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - name: Setup Bundler
        run: |
          set -x
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Update versions
        run: |
          set -x
          sed -i -e 's/    versionCode \([0-9]*\)/echo \"    versionCode\" $((\1 + 1))/eg' version.txt
          sed -i -e 's/    major = \([0-9]*\)/echo \"    major =\" ${{ github.event.inputs.major_version }}/eg' version.txt
          sed -i -e 's/    minor = \([0-9]*\)/echo \"    minor =\" ${{ github.event.inputs.minor_version }}/eg' version.txt
          sed -i -e 's/    patch = \([0-9]*\)/echo \"    patch =\" ${{ github.event.inputs.patch_version }}/eg' version.txt
          cat version.txt
      - name: Update release note
        env:
          REPOSITORY: ${{ github.repository }}
        run: bundle exec ruby update_release_note.rb
      - name: Create pull request
        env:
          VERSION: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}
          MAJOR_VERSION: ${{ github.event.inputs.major_version }}
          MINOR_VERSION: ${{ github.event.inputs.minor_version }}
          PATCH_VERSION: ${{ github.event.inputs.patch_version }}
        run: |
          set -x
          git config user.name github-actions
          git config user.email github-actions@github.com
          branchName=$(printf "feature/update-to-v%02d%02d%02d\n" $MAJOR_VERSION $MINOR_VERSION $PATCH_VERSION)
          git checkout -b $branchName
          git add release_note.txt version.txt
          git commit -m "Update to $VERSION"
          git push origin $branchName
          gh pr create --title "バージョン$VERSIONに更新" --body "$(cat pull_request_message.txt)"
