name: Generate dependency diff

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: dependency-diff
        name: Generate dependency diff
        uses: r-n-i/dependency-tree-diff-action@master
        if: ${{ github.event_name == 'pull_request' }}
      - uses: r-n-i/find-comment@main
        if: ${{ github.event_name == 'pull_request' }}
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "Dependency diff (差分を確認してください):"
      - uses: r-n-i/create-or-update-comment@main
        if: ${{ github.event_name == 'pull_request' && steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff (差分を確認してください):
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
