name: Generate dependency diff

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        if: ${{ github.event_name == 'pull_request' }}
      - uses: peter-evans/find-comment@v1
        name: Find comment
        if: ${{ steps.dependency-diff.conclusion != 'skipped' }}
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "Dependency diff:"
      - uses: peter-evans/create-or-update-comment@v1
        name: Create or update diff comment
        id: create_or_update_diff
        if: ${{ steps.find-comment.conclusion != 'skipped' && steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-or-update-comment@v1
        name: Create or upsate no diff comment
        if: ${{ steps.create_or_update_diff.conclusion == 'skipped' &&  steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff: 依存ライブラリに変更はありません
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
