name: OnPullRequest
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          sleep 10m
          echo ${{ github.event.pull_request.title }}
