name: OnPullRequest
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{ github.workflow }}-${{ github.ref }}
          echo ${{ github.event.pull_request.title }}
          echo hogehoge > release_note.txt
      - name: Check diff
        run: |
          if [! git diff --exit-code --quiet]; then
            echo "diff"
          else
            echo "no-diff
          fi
          
