name: OnPullRequestTarget
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency: OnPullRequestTarget-job-1
    steps:
      - name: Echo
        run: |
          echo job-1 > release_note.txt
      - name: Check diff
        run: |
          if ! git diff --exit-code --quiet
          then
            echo "diff"
          fi
          
  job-2:
    runs-on: ubuntu-latest
    concurrency: 
      group: OnPullRequestTarget-job-2
      cancel-in-progress: true
    steps:
      - name: Echo
        run: | 
          echo job-2
