name: OnPullRequestTarget
on:
  pull_request_target:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo pull_request_target
          echo ${{ github.event.pull_request.title }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: echo version.txt
