name: OnPullRequestTarget
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo job-1
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: | 
          echo job-2
