name: OnPullRequest
on:
  pull_request_target:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo changed
          echo ${{ github.event.pull_request.title }}
