name: workflow_dispatch_test
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version'
        required: true
      minor_version:
        description: 'Minor version'
        required: true 
      patch_version:
        description: 'Patch version'
        required: true
      message:
        default:
          メッセージを
          入力して下さい

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}
          echo ${{ github.event.inputs.message }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git Log
        run: git log
