name: workflow_dispatch_test
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version'
        required: true
      minor_version:
        description: 'Minor version'
        required: true 
      patch_version:
        description: 'Patch version'
        required: true
      message:
        default:
          メッセージを入力して下さい

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check branch
        run: |
          git branch

