name: workflow_dispatch_test
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version'
        required: true
      minor_version:
        description: 'Minor version'
        required: true 
      patch_version:
        description: 'Patch version'
        required: true
      message:
        default:
          メッセージを
          入力して下さい

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}
          echo ${{ github.event.inputs.message }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Branch
        run: |
          echo $VERSION
          echo $MESSAGE
          echo $BRANCH_NAME
          #git checkout -b BRANCH_NAME
          #echo $VERSION > version.txt
          #echo $MESSAGE > message.txt
          #git commit -m "Update to $VERSION" -a
          #git push 
        env: 
          VERSION: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }} > version.txt
          MESSAGE: ${{ github.event.inputs.message }}
          BRANCH_NAME: $(printf "feature/update-to-v%02d%02d%02d\n" $MAJOR_VERSION $MINOR_VERSION $PATCH_VERSION)
